version: "2"
services:
  web:
   build: .
   # image: jperump/secretspace:aa_webapp
   #image: webapp
   ports:
      - "80:3000"
   depends_on:
      - "mongodb"
   links:
      - "mongodb"
   container_name: webapp
   volumes:
      - ./data/images/icons:/srv/app/public/img/icons
      - ./data/images/photos:/srv/app/public/img/photos
      - ./data/images/Slot_1_Image:/srv/app/public/img/Slot_1_Image
      - ./data/images/Slot_2_Image:/srv/app/public/img/Slot_2_Image
      - ./data/images/Slot_3_Image:/srv/app/public/img/Slot_3_Image
      - ./data/images/Slot_4_Image:/srv/app/public/img/Slot_4_Image
      - ./data/images/Slot_5_Image:/srv/app/public/img/Slot_5_Image
  mongodb:
   image: mongo
   ports:
      - "27017:27017"
   container_name: mongodb
   volumes:
      - ./data/database:/data/db
volumes:
   images: 
   database: